apiVersion: v1
kind: Service
metadata:
  name: ridesphere-frontend
  labels:
    app.kubernetes.io/name: ridesphere
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ridesphere
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
